# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rocky <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/25 18:53:30 by rocky             #+#    #+#              #
#    Updated: 2024/08/25 18:53:32 by rocky            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

megaphone: megaphone.o
	g++ megaphone.o -o megaphone

megaphone.o: megaphone.cpp
	g++ -c megaphone.cpp

clean:
	rm *.o

fclean:
	rm *.o megaphone


